"""
tracking/track_attributes.py
==============================
Aggregates UPAR attribute predictions across temporal crops for each tracked pedestrian.

Reads:
- crops_dir: reports/tracking/crops/track_<id>/frame_<n>.jpg
- tracks_csv: reports/tracking/real_pedestrians_tracks.csv
- checkpoint: checkpoints/hydraplus_upar_best.pth

Outputs:
- reports/tracking/track_attributes.csv
- reports/tracking/track_attributes.json
- reports/tracking/tracked_persons_summary.csv
"""

import os
import sys
import json
import time
import argparse
from pathlib import Path
from collections import defaultdict
import csv as csv_module

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from models.hydraplus.par_model import UnifiedPARModel
from datasets.upar.loader import UPAR_ATTRIBUTES, get_upar_transforms

# Label definitions corresponding to model head outputs
AGE_LABELS = ["Young", "Adult", "Old"]
HAIR_LABELS = ["Short", "Long", "Bald"]
COLOR_NAMES = [
    "Black", "Blue", "Brown", "Green", "Grey",
    "Orange", "Pink", "Purple", "Red", "White", "Yellow", "Other"
]
LOWER_TYPE_LABELS = ["Trousers&Shorts", "Skirt&Dress"]
BAG_LABELS = ["Backpack", "Bag"]
GLASSES_LABELS = ["Normal Glasses", "Sunglasses"]

MULTI_LABEL_HEADS = ["hair", "glasses", "upper_color", "lower_color", "lower_type", "bag"]


def parse_args():
    parser = argparse.ArgumentParser(description="Aggregate UPAR attributes for tracked pedestrians")
    parser.add_argument("--crops-dir", type=str, default="reports/tracking/crops",
                        help="Path to folder containing crop subdirectories (e.g. track_1/)")
    parser.add_argument("--tracks-csv", type=str, default="reports/tracking/real_pedestrians_tracks.csv",
                        help="Path to tracking CSV file generated by track.py")
    parser.add_argument("--checkpoint", type=str, default="checkpoints/hydraplus_upar_best.pth",
                        help="Path to UPAR model checkpoint")
    parser.add_argument("--output-dir", type=str, default="reports/tracking",
                        help="Output directory for generated CSV and JSON reports")
    parser.add_argument("--min-frames", type=int, default=3,
                        help="Minimum crops required to process a track")
    parser.add_argument("--threshold", type=float, default=0.5,
                        help="Confidence threshold for multi-label attributes in JSON output")
    return parser.parse_args()


def load_track_metadata(csv_path: str):
    """
    Parse tracks CSV to extract first_seen and last_seen frame & timestamp per track_id.
    Returns dict: track_id -> {first_seen_frame, last_seen_frame, first_seen_time, last_seen_time}
    """
    tracks_meta = {}
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv_module.DictReader(f)
        for row in reader:
            t_id = int(row["track_id"])
            frame_id = int(row["frame_id"])
            timestamp = float(row["timestamp"])

            if t_id not in tracks_meta:
                tracks_meta[t_id] = {
                    "first_seen_frame": frame_id,
                    "last_seen_frame": frame_id,
                    "first_seen_time": timestamp,
                    "last_seen_time": timestamp
                }
            else:
                if frame_id < tracks_meta[t_id]["first_seen_frame"]:
                    tracks_meta[t_id]["first_seen_frame"] = frame_id
                    tracks_meta[t_id]["first_seen_time"] = timestamp
                if frame_id > tracks_meta[t_id]["last_seen_frame"]:
                    tracks_meta[t_id]["last_seen_frame"] = frame_id
                    tracks_meta[t_id]["last_seen_time"] = timestamp

    return tracks_meta


def load_par_model(checkpoint_path: str, device: torch.device) -> UnifiedPARModel:
    """Load model checkpoint cleanly without altering inference logic."""
    model = UnifiedPARModel(num_attributes=40, backbone_name='resnet50', pretrained=True).to(device)
    if os.path.exists(checkpoint_path):
        checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
        state_dict = checkpoint["model_state_dict"] if "model_state_dict" in checkpoint else checkpoint
        model.load_state_dict(state_dict)
        print(f"[INFO] Successfully loaded model checkpoint: {checkpoint_path}")
    else:
        raise FileNotFoundError(f"[ERROR] Checkpoint file not found: {checkpoint_path}")
    model.eval()
    return model


@torch.no_grad()
def predict_crop_probabilities(model: UnifiedPARModel, crop_paths: list, transform, device: torch.device):
    """
    Run forward pass on all crops of a track.
    Returns dict: head_name -> np.ndarray of probabilities across crop images (shape [N, head_dim]).
    """
    tensors = []
    for p in crop_paths:
        img = Image.open(p).convert("RGB")
        tensors.append(transform(img))
    
    batch = torch.stack(tensors).to(device)
    logits_dict = model(batch)

    head_probs = {
        "age": F.softmax(logits_dict["age"], dim=1).cpu().numpy(),
        "gender": torch.sigmoid(logits_dict["gender"]).cpu().numpy(),
        "hair": torch.sigmoid(logits_dict["hair"]).cpu().numpy(),
        "upper_length": torch.sigmoid(logits_dict["upper_length"]).cpu().numpy(),
        "upper_color": torch.sigmoid(logits_dict["upper_color"]).cpu().numpy(),
        "lower_length": torch.sigmoid(logits_dict["lower_length"]).cpu().numpy(),
        "lower_color": torch.sigmoid(logits_dict["lower_color"]).cpu().numpy(),
        "lower_type": torch.sigmoid(logits_dict["lower_type"]).cpu().numpy(),
        "bag": torch.sigmoid(logits_dict["bag"]).cpu().numpy(),
        "glasses": torch.sigmoid(logits_dict["glasses"]).cpu().numpy(),
        "hat": torch.sigmoid(logits_dict["hat"]).cpu().numpy(),
    }
    return head_probs


def aggregate_track_predictions(head_probs: dict, threshold: float = 0.5):
    """
    Computes mean probabilities across frames per head and extracts:
    - top1_summary: dict of attributes with top-1 labels & confidences (for CSV)
    - multi_label_summary: dict of multi-label active lists (for JSON)
    - raw_40_probs: dict of 40 UPAR attribute probabilities
    """
    mean_probs = {h: np.mean(probs, axis=0) for h, probs in head_probs.items()}

    # --- Top-1 Extraction for CSV ---
    top1_summary = {}

    # 1. Age (Softmax 3 classes -> argmax)
    age_idx = int(np.argmax(mean_probs["age"]))
    top1_summary["age"] = AGE_LABELS[age_idx]
    top1_summary["age_conf"] = float(mean_probs["age"][age_idx])

    # 2. Gender (Binary)
    g_prob = float(mean_probs["gender"][0])
    if g_prob >= 0.5:
        top1_summary["gender"] = "Female"
        top1_summary["gender_conf"] = g_prob
    else:
        top1_summary["gender"] = "Male"
        top1_summary["gender_conf"] = 1.0 - g_prob

    # 3. Hair (Multi-label -> top-1)
    hair_idx = int(np.argmax(mean_probs["hair"]))
    top1_summary["hair"] = HAIR_LABELS[hair_idx]
    top1_summary["hair_conf"] = float(mean_probs["hair"][hair_idx])

    # 4. Upper Length (Binary)
    ul_prob = float(mean_probs["upper_length"][0])
    if ul_prob >= 0.5:
        top1_summary["upper_length"] = "Short"
        top1_summary["upper_length_conf"] = ul_prob
    else:
        top1_summary["upper_length"] = "Long"
        top1_summary["upper_length_conf"] = 1.0 - ul_prob

    # 5. Upper Color (Multi-label -> top-1)
    uc_idx = int(np.argmax(mean_probs["upper_color"]))
    top1_summary["upper_color"] = COLOR_NAMES[uc_idx]
    top1_summary["upper_color_conf"] = float(mean_probs["upper_color"][uc_idx])

    # 6. Lower Length (Binary)
    ll_prob = float(mean_probs["lower_length"][0])
    if ll_prob >= 0.5:
        top1_summary["lower_length"] = "Short"
        top1_summary["lower_length_conf"] = ll_prob
    else:
        top1_summary["lower_length"] = "Long"
        top1_summary["lower_length_conf"] = 1.0 - ll_prob

    # 7. Lower Color (Multi-label -> top-1)
    lc_idx = int(np.argmax(mean_probs["lower_color"]))
    top1_summary["lower_color"] = COLOR_NAMES[lc_idx]
    top1_summary["lower_color_conf"] = float(mean_probs["lower_color"][lc_idx])

    # 8. Lower Type (Multi-label -> top-1)
    lt_idx = int(np.argmax(mean_probs["lower_type"]))
    top1_summary["lower_type"] = LOWER_TYPE_LABELS[lt_idx]
    top1_summary["lower_type_conf"] = float(mean_probs["lower_type"][lt_idx])

    # 9. Bag (Multi-label: None if max < threshold else top-1)
    bag_max_conf = float(np.max(mean_probs["bag"]))
    if bag_max_conf >= threshold:
        bag_idx = int(np.argmax(mean_probs["bag"]))
        top1_summary["bag"] = BAG_LABELS[bag_idx]
    else:
        top1_summary["bag"] = "None"
    top1_summary["bag_conf"] = bag_max_conf

    # 10. Glasses (Multi-label: None if max < threshold else top-1)
    gl_max_conf = float(np.max(mean_probs["glasses"]))
    if gl_max_conf >= threshold:
        gl_idx = int(np.argmax(mean_probs["glasses"]))
        top1_summary["glasses"] = GLASSES_LABELS[gl_idx]
    else:
        top1_summary["glasses"] = "None"
    top1_summary["glasses_conf"] = gl_max_conf

    # 11. Hat (Binary)
    hat_prob = float(mean_probs["hat"][0])
    if hat_prob >= 0.5:
        top1_summary["hat"] = "Hat"
        top1_summary["hat_conf"] = hat_prob
    else:
        top1_summary["hat"] = "No Hat"
        top1_summary["hat_conf"] = 1.0 - hat_prob

    # --- Multi-label Full Extraction for JSON ---
    multi_label_summary = {}

    head_label_maps = {
        "hair": HAIR_LABELS,
        "glasses": GLASSES_LABELS,
        "upper_color": COLOR_NAMES,
        "lower_color": COLOR_NAMES,
        "lower_type": LOWER_TYPE_LABELS,
        "bag": BAG_LABELS,
    }

    for h_name in MULTI_LABEL_HEADS:
        labels = head_label_maps[h_name]
        active_list = []
        for idx, prob in enumerate(mean_probs[h_name]):
            prob_val = float(prob)
            if prob_val >= threshold:
                active_list.append({"label": labels[idx], "confidence": round(prob_val, 4)})
        multi_label_summary[h_name] = active_list

    # --- 40 Raw Attribute Probabilities Vector ---
    raw_40_vector = np.concatenate([
        mean_probs["age"],           # 3
        mean_probs["gender"],        # 1
        mean_probs["hair"],          # 3
        mean_probs["upper_length"],  # 1
        mean_probs["upper_color"],   # 12
        mean_probs["lower_length"],  # 1
        mean_probs["lower_color"],   # 12
        mean_probs["lower_type"],    # 2
        mean_probs["bag"],           # 2
        mean_probs["glasses"],       # 2
        mean_probs["hat"]            # 1
    ])

    raw_40_probs = {UPAR_ATTRIBUTES[i]: round(float(raw_40_vector[i]), 4) for i in range(len(UPAR_ATTRIBUTES))}

    return top1_summary, multi_label_summary, raw_40_probs


def main():
    args = parse_args()

    crops_dir = Path(args.crops_dir)
    tracks_csv = Path(args.tracks_csv)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not crops_dir.exists():
        raise FileNotFoundError(f"[ERROR] Crops directory does not exist: {crops_dir}")
    if not tracks_csv.exists():
        raise FileNotFoundError(f"[ERROR] Tracks CSV does not exist: {tracks_csv}")

    print("=" * 70)
    print("UPAR TRACK-LEVEL ATTRIBUTE AGGREGATION")
    print("=" * 70)
    print(f"Crops Directory : {crops_dir.resolve()}")
    print(f"Tracks CSV      : {tracks_csv.resolve()}")
    print(f"Checkpoint      : {Path(args.checkpoint).resolve()}")
    print(f"Min Frames      : {args.min_frames}")
    print(f"Threshold       : {args.threshold}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device          : {device}")

    # Load model and transforms
    model = load_par_model(args.checkpoint, device)
    _, val_transform = get_upar_transforms(256, 128)

    # Load track metadata
    tracks_meta = load_track_metadata(str(tracks_csv))

    # Find track crop folders
    track_folders = sorted(
        [d for d in crops_dir.iterdir() if d.is_dir() and d.name.startswith("track_")],
        key=lambda x: int(x.name.split("_")[1]) if x.name.split("_")[1].isdigit() else x.name
    )

    print(f"[INFO] Found {len(track_folders)} track crop folder(s).")

    csv_rows = []
    summary_rows = []
    json_output = {}

    inference_times = []

    for track_folder in track_folders:
        track_id = int(track_folder.name.split("_")[1])
        crop_files = sorted(
            [f for f in track_folder.iterdir() if f.suffix.lower() in [".jpg", ".png", ".jpeg"]],
            key=lambda x: int(x.stem.split("_")[1]) if len(x.stem.split("_")) > 1 and x.stem.split("_")[1].isdigit() else x.name
        )

        n_frames = len(crop_files)
        if n_frames < args.min_frames:
            print(f"[SKIP] Track {track_id}: only {n_frames} crops (< min_frames {args.min_frames})")
            continue

        start_time = time.time()
        head_probs = predict_crop_probabilities(model, [str(f) for f in crop_files], val_transform, device)
        elapsed = time.time() - start_time
        inference_times.append(elapsed)

        top1_summary, multi_label_summary, raw_40_probs = aggregate_track_predictions(head_probs, threshold=args.threshold)

        # Build CSV row dict
        attr_csv_row = {
            "track_id": track_id,
            "n_frames_used": n_frames,
            "age": top1_summary["age"],
            "age_conf": round(top1_summary["age_conf"], 4),
            "gender": top1_summary["gender"],
            "gender_conf": round(top1_summary["gender_conf"], 4),
            "hair": top1_summary["hair"],
            "hair_conf": round(top1_summary["hair_conf"], 4),
            "glasses": top1_summary["glasses"],
            "glasses_conf": round(top1_summary["glasses_conf"], 4),
            "hat": top1_summary["hat"],
            "hat_conf": round(top1_summary["hat_conf"], 4),
            "upper_length": top1_summary["upper_length"],
            "upper_length_conf": round(top1_summary["upper_length_conf"], 4),
            "upper_color": top1_summary["upper_color"],
            "upper_color_conf": round(top1_summary["upper_color_conf"], 4),
            "lower_length": top1_summary["lower_length"],
            "lower_length_conf": round(top1_summary["lower_length_conf"], 4),
            "lower_color": top1_summary["lower_color"],
            "lower_color_conf": round(top1_summary["lower_color_conf"], 4),
            "lower_type": top1_summary["lower_type"],
            "lower_type_conf": round(top1_summary["lower_type_conf"], 4),
            "bag": top1_summary["bag"],
            "bag_conf": round(top1_summary["bag_conf"], 4),
        }
        csv_rows.append(attr_csv_row)

        # Build summary row (with tracking metadata)
        meta = tracks_meta.get(track_id, {
            "first_seen_frame": -1, "last_seen_frame": -1,
            "first_seen_time": -1.0, "last_seen_time": -1.0
        })

        summary_row = {
            "track_id": track_id,
            "first_seen_frame": meta["first_seen_frame"],
            "last_seen_frame": meta["last_seen_frame"],
            "first_seen_time": meta["first_seen_time"],
            "last_seen_time": meta["last_seen_time"],
            "n_frames_used": n_frames,
            "age": attr_csv_row["age"],
            "age_conf": attr_csv_row["age_conf"],
            "gender": attr_csv_row["gender"],
            "gender_conf": attr_csv_row["gender_conf"],
            "hair": attr_csv_row["hair"],
            "hair_conf": attr_csv_row["hair_conf"],
            "glasses": attr_csv_row["glasses"],
            "glasses_conf": attr_csv_row["glasses_conf"],
            "hat": attr_csv_row["hat"],
            "hat_conf": attr_csv_row["hat_conf"],
            "upper_length": attr_csv_row["upper_length"],
            "upper_length_conf": attr_csv_row["upper_length_conf"],
            "upper_color": attr_csv_row["upper_color"],
            "upper_color_conf": attr_csv_row["upper_color_conf"],
            "lower_length": attr_csv_row["lower_length"],
            "lower_length_conf": attr_csv_row["lower_length_conf"],
            "lower_color": attr_csv_row["lower_color"],
            "lower_color_conf": attr_csv_row["lower_color_conf"],
            "lower_type": attr_csv_row["lower_type"],
            "lower_type_conf": attr_csv_row["lower_type_conf"],
            "bag": attr_csv_row["bag"],
            "bag_conf": attr_csv_row["bag_conf"],
        }
        summary_rows.append(summary_row)

        # Build JSON dictionary for track
        json_output[str(track_id)] = {
            "track_id": track_id,
            "n_frames_used": n_frames,
            "first_seen_frame": meta["first_seen_frame"],
            "last_seen_frame": meta["last_seen_frame"],
            "first_seen_time": meta["first_seen_time"],
            "last_seen_time": meta["last_seen_time"],
            "top1_summary": top1_summary,
            "multi_label_heads": multi_label_summary,
            "raw_probabilities_40": raw_40_probs
        }

        print(f"[PROC] Track {track_id:2d}: {n_frames:2d} crops | Time: {elapsed*1000:6.2f}ms | Gender: {top1_summary['gender']} ({top1_summary['gender_conf']*100:.1f}%) | Upper: {top1_summary['upper_color']} | Lower: {top1_summary['lower_color']}")

    # --- Write Outputs ---
    csv_file = output_dir / "track_attributes.csv"
    csv_fieldnames = list(csv_rows[0].keys()) if csv_rows else []
    with open(csv_file, "w", newline="", encoding="utf-8") as f:
        writer = csv_module.DictWriter(f, fieldnames=csv_fieldnames)
        writer.writeheader()
        writer.writerows(csv_rows)
    print(f"\n[OUTPUT] Saved track attributes CSV: {csv_file.resolve()}")

    json_file = output_dir / "track_attributes.json"
    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(json_output, f, indent=2)
    print(f"[OUTPUT] Saved track attributes JSON: {json_file.resolve()}")

    # Also save as attributes.json for pipeline consistency
    attr_json_file = output_dir / "attributes.json"
    with open(attr_json_file, "w", encoding="utf-8") as f:
        json.dump(json_output, f, indent=2)
    print(f"[OUTPUT] Saved attributes JSON: {attr_json_file.resolve()}")

    summary_file = output_dir / "tracked_persons_summary.csv"
    summary_fieldnames = list(summary_rows[0].keys()) if summary_rows else []
    with open(summary_file, "w", newline="", encoding="utf-8") as f:
        writer = csv_module.DictWriter(f, fieldnames=summary_fieldnames)
        writer.writeheader()
        writer.writerows(summary_rows)
    print(f"[OUTPUT] Saved tracked persons summary CSV: {summary_file.resolve()}")

    # Summary Benchmark
    avg_time = np.mean(inference_times) if inference_times else 0.0
    print("\n" + "=" * 70)
    print("SUMMARY BENCHMARK REPORT")
    print("=" * 70)
    print(f"Total Tracks Processed   : {len(csv_rows)}")
    print(f"Average Inference / Track: {avg_time*1000:.2f} ms ({avg_time:.4f} s)")
    print(f"Estimated FPS / Track    : {1.0 / avg_time if avg_time > 0 else 0:.2f} tracks/sec")
    print("=" * 70)


if __name__ == "__main__":
    main()
